"""empty message

Revision ID: 44a7747ec3e2
Revises: 716e0dac32ac
Create Date: 2023-05-01 12:21:49.945609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44a7747ec3e2'
down_revision = '716e0dac32ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('review_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('yelp_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_column('yelp_id')
        batch_op.drop_column('review_count')
        batch_op.drop_column('rating')
        batch_op.drop_column('image_url')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
