"""empty message

Revision ID: b02ab2dbce34
Revises: 1e2a6b74acb3
Create Date: 2023-05-03 20:52:56.537910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b02ab2dbce34'
down_revision = '1e2a6b74acb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_restaurants')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_restaurants',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('restaurant_id', sa.INTEGER(), nullable=True),
    sa.Column('last_visit', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name='fk_favorite_restaurants_restaurant_id_restaurants'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_favorite_restaurants_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
